---
- name: OpenSSL
  hosts: company_server
  become: yes 
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id25519
  tasks:
    - name: Install required packages
      apt:
        name: install openssl
         state: present
      loop:
        - openssl
        - python3-cryptography  # This is the package name for cryptography library in Ubuntu/Debian
        - python3-pip 
	- python3-packaging 
      when: ansible_pkg_mgr == "apt" # Install pip to ensure the availability of Python package manager

    # Check if python3-cryptography is installed
    - name: Check if python3-cryptography is installed
      command: dpkg -l | grep python3-cryptography
      register: cryptography_check
      changed_when: false
      failed_when: false
      
    - name: Generate CA key
      openssl_privatekey:
        path: /etc/ssl/private/ca.key
        size: 4096
      register: ca_ssl_key

    - name: Generate CA certificate 
      openssl_csr:
        path: /etc/ssl/certs/ca.csr
        privatekey_path: /etc/ssl/private/ca.key
        common_name: "CA WITH SSL"
        country_name: "PH"
        state_or_province_name: "Metro Manila"
        locality_name: "Pantranco - Quezon City"
        organization_name: "Hilflyer canada"
        email_address: "mainaddress@gmail.com"
      register: ca_csr

    - name: Self-signed CA certificate
      openssl_certificate:
        path: /etc/ssl/certs/ca.crt
        privatekey_path: /etc/ssl/private/ca.key
        csr_path: /etc/ssl/certs/ca.csr
        provider: selfsigned
        force: true
